"""add unique constraint to politician aliases

Revision ID: 007107b47b16
Revises: 287044aaa710
Create Date: 2026-08-16 14:45:42.343718

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '007107b47b16'
down_revision: Union[str, Sequence[str], None] = '287044aaa710'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_politician_aliases_politician_id_alias', 'politician_aliases', ['politician_id', 'alias'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_politician_aliases_politician_id_alias', 'politician_aliases', type_='unique')
    # ### end Alembic commands ###
