"""create politicians table

Revision ID: 044e8dce8e43
Revises: 
Create Date: 2026-08-14 12:23:51.147111

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '044e8dce8e43'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('politicians',
    sa.Column('politician_id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=150), nullable=False),
    sa.Column('slug', sa.String(length=150), nullable=False),
    sa.Column('party', sa.String(length=150), nullable=True),
    sa.Column('current_position', sa.String(length=150), nullable=True),
    sa.Column('profile_image_url', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('politician_id')
    )    
    op.create_index(op.f('ix_politicians_slug'), 'politicians', ['slug'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_politicians_slug'), table_name='politicians')
    op.drop_index(op.f('ix_politicians_politician_id'), table_name='politicians')
    op.drop_table('politicians')
    # ### end Alembic commands ###
