"""create sentiment analyses table

Revision ID: 287044aaa710
Revises: ccfedb91341e
Create Date: 2026-08-14 15:51:04.571853

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '287044aaa710'
down_revision: Union[str, Sequence[str], None] = 'ccfedb91341e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sentiment_analyses',
    sa.Column('analysis_id', sa.Integer(), nullable=False),
    sa.Column('mention_id', sa.Integer(), nullable=False),
    sa.Column('model_version', sa.String(length=100), nullable=False),
    sa.Column('sentiment_label', sa.String(length=20), nullable=False),
    sa.Column('confidence_score', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('analyzed_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['mention_id'], ['mentions.mention_id'], ),
    sa.PrimaryKeyConstraint('analysis_id'),
    sa.UniqueConstraint('mention_id', 'model_version', name='uq_sentiment_analyses_mention_model')
    )
    op.create_index(op.f('ix_sentiment_analyses_mention_id'), 'sentiment_analyses', ['mention_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sentiment_analyses_mention_id'), table_name='sentiment_analyses')
    op.drop_table('sentiment_analyses')
    # ### end Alembic commands ###
