"""create politician aliases table

Revision ID: 575205768e23
Revises: 044e8dce8e43
Create Date: 2026-08-14 12:45:25.557252

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '575205768e23'
down_revision: Union[str, Sequence[str], None] = '044e8dce8e43'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('politician_aliases',
    sa.Column('alias_id', sa.Integer(), nullable=False),
    sa.Column('politician_id', sa.Integer(), nullable=False),
    sa.Column('alias', sa.String(length=150), nullable=False),
    sa.Column('alias_type', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['politician_id'], ['politicians.politician_id'], ),
    sa.PrimaryKeyConstraint('alias_id')
    )
    op.create_index(op.f('ix_politician_aliases_politician_id'), 'politician_aliases', ['politician_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_politician_aliases_politician_id'), table_name='politician_aliases')
    op.drop_table('politician_aliases')
    # ### end Alembic commands ###
