"""add compound score to sentiment analyses

Revision ID: 5b197b6ede93
Revises: 007107b47b16
Create Date: 2026-09-25 16:43:27.040614

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5b197b6ede93'
down_revision: Union[str, Sequence[str], None] = '007107b47b16'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sentiment_analyses', sa.Column('compound_score', sa.Numeric(precision=5, scale=4), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sentiment_analyses', 'compound_score')
    # ### end Alembic commands ###
