"""create mentions table

Revision ID: ccfedb91341e
Revises: a5d31553b315
Create Date: 2026-08-14 15:38:57.588313

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ccfedb91341e'
down_revision: Union[str, Sequence[str], None] = 'a5d31553b315'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mentions',
    sa.Column('mention_id', sa.Integer(), nullable=False),
    sa.Column('comment_id', sa.Integer(), nullable=False),
    sa.Column('politician_id', sa.Integer(), nullable=False),
    sa.Column('relevance_score', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('detected_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['comment_id'], ['comments.comment_id'], ),
    sa.ForeignKeyConstraint(['politician_id'], ['politicians.politician_id'], ),
    sa.PrimaryKeyConstraint('mention_id'),
    sa.UniqueConstraint('comment_id', 'politician_id', name='uq_mentions_comment_politician')
    )
    op.create_index(op.f('ix_mentions_comment_id'), 'mentions', ['comment_id'], unique=False)
    op.create_index(op.f('ix_mentions_politician_id'), 'mentions', ['politician_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_mentions_politician_id'), table_name='mentions')
    op.drop_index(op.f('ix_mentions_comment_id'), table_name='mentions')
    op.drop_table('mentions')
    # ### end Alembic commands ###
