"""create source politicians table

Revision ID: fb37f7fb819b
Revises: dc6c3b785a6e
Create Date: 2026-08-14 14:09:26.932032

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fb37f7fb819b'
down_revision: Union[str, Sequence[str], None] = 'dc6c3b785a6e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('source_politicians',
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('politician_id', sa.Integer(), nullable=False),
    sa.Column('added_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['politician_id'], ['politicians.politician_id'], ),
    sa.ForeignKeyConstraint(['source_id'], ['sources.source_id'], ),
    sa.PrimaryKeyConstraint('source_id', 'politician_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('source_politicians')
    # ### end Alembic commands ###
